### ISSUE TITLE
How to turn off the attitude estimation module？

### ISSUE THREAD

**Issue by weilenglxl** [theoway/multi-cam-reid#2]
Hi,thanks your great repo.
I have a question about "How to turn off the attitude estimation module ?"

**Comment by theoway** [comment]
Thanks! Glad to hear you liked it... I'd love it if you can start the repo ⭐
By attitude, I think you mean pose estimation. It can be turned off manually but I'll make a PR to pass an argument to command line to turn it on and off 😊

**Comment by weilenglxl** [comment]
⭐~ 
Okay, thanks for the help.

**Comment by weilenglxl** [comment]
Excuse me, I want to ask how the progress is, and is this repo adaptable to processing four RTSP streams simultaneously?😊

**Comment by theoway** [comment]
@weilenglxl Sorry for the late reply... You can now use pose estimation as well. Just use `-p` when running the tool. 
I don't know if it'll work with 4. I have tested with 2 parallel streams, got decent results without pose estimation. Really depends on the hardware. 
Please tell me your use case. Maybe we can build something better together :)
